/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualLabRouteImport } from './routes/virtual-lab'
import { Route as SmartBoardRouteImport } from './routes/smart-board'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'

const VirtualLabRoute = VirtualLabRouteImport.update({
  id: '/virtual-lab',
  path: '/virtual-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartBoardRoute = SmartBoardRouteImport.update({
  id: '/smart-board',
  path: '/smart-board',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/slides': typeof SlidesRoute
  '/smart-board': typeof SmartBoardRoute
  '/virtual-lab': typeof VirtualLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/slides': typeof SlidesRoute
  '/smart-board': typeof SmartBoardRoute
  '/virtual-lab': typeof VirtualLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/slides': typeof SlidesRoute
  '/smart-board': typeof SmartBoardRoute
  '/virtual-lab': typeof VirtualLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/slides' | '/smart-board' | '/virtual-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/slides' | '/smart-board' | '/virtual-lab'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/slides'
    | '/smart-board'
    | '/virtual-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SlidesRoute: typeof SlidesRoute
  SmartBoardRoute: typeof SmartBoardRoute
  VirtualLabRoute: typeof VirtualLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-lab': {
      id: '/virtual-lab'
      path: '/virtual-lab'
      fullPath: '/virtual-lab'
      preLoaderRoute: typeof VirtualLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-board': {
      id: '/smart-board'
      path: '/smart-board'
      fullPath: '/smart-board'
      preLoaderRoute: typeof SmartBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SlidesRoute: SlidesRoute,
  SmartBoardRoute: SmartBoardRoute,
  VirtualLabRoute: VirtualLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
